var annotated =
[
    [ "edm", "namespaceedm.html", "namespaceedm" ],
    [ "ic", "namespaceic.html", "namespaceic" ],
    [ "CollectionIDAndSize", "struct_collection_i_d_and_size.html", "struct_collection_i_d_and_size" ],
    [ "CollectionSize", "struct_collection_size.html", "struct_collection_size" ],
    [ "EGammaMvaEleEstimatorCSA14", "class_e_gamma_mva_ele_estimator_c_s_a14.html", "class_e_gamma_mva_ele_estimator_c_s_a14" ],
    [ "ICCandidateFromL1MuonProducer", "class_i_c_candidate_from_l1_muon_producer.html", "class_i_c_candidate_from_l1_muon_producer" ],
    [ "ICCandidateProducer", "class_i_c_candidate_producer.html", "class_i_c_candidate_producer" ],
    [ "ICConversionProducer", "class_i_c_conversion_producer.html", "class_i_c_conversion_producer" ],
    [ "ICElectronConversionCalculator", "class_i_c_electron_conversion_calculator.html", "class_i_c_electron_conversion_calculator" ],
    [ "ICElectronConversionFromPatCalculator", "class_i_c_electron_conversion_from_pat_calculator.html", "class_i_c_electron_conversion_from_pat_calculator" ],
    [ "ICElectronHcalDepthCalculator", "class_i_c_electron_hcal_depth_calculator.html", "class_i_c_electron_hcal_depth_calculator" ],
    [ "ICElectronIDMVAProducerMiniAOD", "class_i_c_electron_i_d_m_v_a_producer_mini_a_o_d.html", "class_i_c_electron_i_d_m_v_a_producer_mini_a_o_d" ],
    [ "ICElectronProducer", "class_i_c_electron_producer.html", "class_i_c_electron_producer" ],
    [ "ICEventInfoProducer", "class_i_c_event_info_producer.html", "class_i_c_event_info_producer" ],
    [ "ICEventProducer", "class_i_c_event_producer.html", "class_i_c_event_producer" ],
    [ "ICGenJetProducer", "class_i_c_gen_jet_producer.html", "class_i_c_gen_jet_producer" ],
    [ "ICGenParticleFromLHEParticlesProducer", "class_i_c_gen_particle_from_l_h_e_particles_producer.html", "class_i_c_gen_particle_from_l_h_e_particles_producer" ],
    [ "ICGenParticleProducer", "class_i_c_gen_particle_producer.html", "class_i_c_gen_particle_producer" ],
    [ "ICGenTauProductProducer", "class_i_c_gen_tau_product_producer.html", "class_i_c_gen_tau_product_producer" ],
    [ "ICGenVertexProducer", "class_i_c_gen_vertex_producer.html", "class_i_c_gen_vertex_producer" ],
    [ "ICHashTreeProducer", "class_i_c_hash_tree_producer.html", "class_i_c_hash_tree_producer" ],
    [ "ICHttElecIsoCheck", "class_i_c_htt_elec_iso_check.html", "class_i_c_htt_elec_iso_check" ],
    [ "ICHttMuonOverlapCheck", "class_i_c_htt_muon_overlap_check.html", "class_i_c_htt_muon_overlap_check" ],
    [ "ICJetFlavourCalculator", "class_i_c_jet_flavour_calculator.html", "class_i_c_jet_flavour_calculator" ],
    [ "ICJetProducer", "class_i_c_jet_producer.html", "class_i_c_jet_producer" ],
    [ "ICL1EtMissProducer", "class_i_c_l1_et_miss_producer.html", "class_i_c_l1_et_miss_producer" ],
    [ "ICLeptonIsolation", "class_i_c_lepton_isolation.html", "class_i_c_lepton_isolation" ],
    [ "ICLightTrackProducer", "class_i_c_light_track_producer.html", "class_i_c_light_track_producer" ],
    [ "ICMetProducer", "class_i_c_met_producer.html", "class_i_c_met_producer" ],
    [ "ICMuonProducer", "class_i_c_muon_producer.html", "class_i_c_muon_producer" ],
    [ "ICPFCandidateProducer", "class_i_c_p_f_candidate_producer.html", "class_i_c_p_f_candidate_producer" ],
    [ "ICPhotonElectronConversionVetoFromPatCalculator", "class_i_c_photon_electron_conversion_veto_from_pat_calculator.html", "class_i_c_photon_electron_conversion_veto_from_pat_calculator" ],
    [ "ICPhotonElectronVetoCalculator", "class_i_c_photon_electron_veto_calculator.html", "class_i_c_photon_electron_veto_calculator" ],
    [ "ICPhotonProducer", "class_i_c_photon_producer.html", "class_i_c_photon_producer" ],
    [ "ICPileupInfoProducer", "class_i_c_pileup_info_producer.html", "class_i_c_pileup_info_producer" ],
    [ "ICSecondaryVertexProducer", "class_i_c_secondary_vertex_producer.html", "class_i_c_secondary_vertex_producer" ],
    [ "ICSingleMetProducer", "class_i_c_single_met_producer.html", "class_i_c_single_met_producer" ],
    [ "ICSuperClusterProducer", "class_i_c_super_cluster_producer.html", "class_i_c_super_cluster_producer" ],
    [ "ICTauProducer", "class_i_c_tau_producer.html", "class_i_c_tau_producer" ],
    [ "ICTrackProducer", "class_i_c_track_producer.html", "class_i_c_track_producer" ],
    [ "ICTriggerObjectProducer", "class_i_c_trigger_object_producer.html", "class_i_c_trigger_object_producer" ],
    [ "ICTriggerPathProducer", "class_i_c_trigger_path_producer.html", "class_i_c_trigger_path_producer" ],
    [ "ICVertexProducer", "class_i_c_vertex_producer.html", "class_i_c_vertex_producer" ],
    [ "JetDestHelper", "struct_jet_dest_helper.html", "struct_jet_dest_helper" ],
    [ "JetDestHelper< ic::CaloJet >", "struct_jet_dest_helper_3_01ic_1_1_calo_jet_01_4.html", "struct_jet_dest_helper_3_01ic_1_1_calo_jet_01_4" ],
    [ "JetDestHelper< ic::JPTJet >", "struct_jet_dest_helper_3_01ic_1_1_j_p_t_jet_01_4.html", "struct_jet_dest_helper_3_01ic_1_1_j_p_t_jet_01_4" ],
    [ "JetDestHelper< ic::PFJet >", "struct_jet_dest_helper_3_01ic_1_1_p_f_jet_01_4.html", "struct_jet_dest_helper_3_01ic_1_1_p_f_jet_01_4" ],
    [ "JetSrcHelper", "struct_jet_src_helper.html", "struct_jet_src_helper" ],
    [ "JetSrcHelper< pat::Jet >", "struct_jet_src_helper_3_01pat_1_1_jet_01_4.html", "struct_jet_src_helper_3_01pat_1_1_jet_01_4" ],
    [ "RequestByDeltaR", "class_request_by_delta_r.html", "class_request_by_delta_r" ]
];