var annotated =
[
    [ "ch::syst::analysis", "structch_1_1syst_1_1analysis.html", "structch_1_1syst_1_1analysis" ],
    [ "ch::syst::bin", "structch_1_1syst_1_1bin.html", "structch_1_1syst_1_1bin" ],
    [ "ch::syst::bin_id", "classch_1_1syst_1_1bin__id.html", "classch_1_1syst_1_1bin__id" ],
    [ "ic::CaloJet", "classic_1_1_calo_jet.html", "classic_1_1_calo_jet" ],
    [ "ic::Candidate", "classic_1_1_candidate.html", "classic_1_1_candidate" ],
    [ "ch::syst::channel", "structch_1_1syst_1_1channel.html", "structch_1_1syst_1_1channel" ],
    [ "ch::CombineHarvester", "classch_1_1_combine_harvester.html", "classch_1_1_combine_harvester" ],
    [ "ic::CompositeCandidate", "classic_1_1_composite_candidate.html", "classic_1_1_composite_candidate" ],
    [ "ic::Concatenate< T >", "classic_1_1_concatenate.html", "classic_1_1_concatenate" ],
    [ "ic::Electron", "classic_1_1_electron.html", "classic_1_1_electron" ],
    [ "ch::syst::era", "structch_1_1syst_1_1era.html", "structch_1_1syst_1_1era" ],
    [ "ic::EventInfo", "classic_1_1_event_info.html", "classic_1_1_event_info" ],
    [ "ic::GenJet", "classic_1_1_gen_jet.html", "classic_1_1_gen_jet" ],
    [ "ic::GenParticle", "classic_1_1_gen_particle.html", "classic_1_1_gen_particle" ],
    [ "ch::HistMapping", "structch_1_1_hist_mapping.html", "structch_1_1_hist_mapping" ],
    [ "ICCandidateProducer", "class_i_c_candidate_producer.html", "class_i_c_candidate_producer" ],
    [ "ICElectronHcalDepthCalculator", "class_i_c_electron_hcal_depth_calculator.html", "class_i_c_electron_hcal_depth_calculator" ],
    [ "ICElectronProducer", "class_i_c_electron_producer.html", "class_i_c_electron_producer" ],
    [ "ICEventInfoProducer", "class_i_c_event_info_producer.html", "class_i_c_event_info_producer" ],
    [ "ICEventProducer", "class_i_c_event_producer.html", "class_i_c_event_producer" ],
    [ "ICGenJetProducer", "class_i_c_gen_jet_producer.html", "class_i_c_gen_jet_producer" ],
    [ "ICGenParticleProducer", "class_i_c_gen_particle_producer.html", "class_i_c_gen_particle_producer" ],
    [ "ICGenTauProductProducer", "class_i_c_gen_tau_product_producer.html", "class_i_c_gen_tau_product_producer" ],
    [ "ICHttElecIsoCheck", "class_i_c_htt_elec_iso_check.html", "class_i_c_htt_elec_iso_check" ],
    [ "ICHttMuonOverlapCheck", "class_i_c_htt_muon_overlap_check.html", "class_i_c_htt_muon_overlap_check" ],
    [ "ICJetFlavourCalculator", "class_i_c_jet_flavour_calculator.html", "class_i_c_jet_flavour_calculator" ],
    [ "ICJetProducer< T, U >", "class_i_c_jet_producer.html", "class_i_c_jet_producer" ],
    [ "ICL1EtMissProducer", "class_i_c_l1_et_miss_producer.html", "class_i_c_l1_et_miss_producer" ],
    [ "ICLightTrackProducer", "class_i_c_light_track_producer.html", "class_i_c_light_track_producer" ],
    [ "ICMetProducer", "class_i_c_met_producer.html", "class_i_c_met_producer" ],
    [ "ICMuonProducer", "class_i_c_muon_producer.html", "class_i_c_muon_producer" ],
    [ "ICPhotonElectronVetoCalculator", "class_i_c_photon_electron_veto_calculator.html", "class_i_c_photon_electron_veto_calculator" ],
    [ "ICPhotonProducer", "class_i_c_photon_producer.html", "class_i_c_photon_producer" ],
    [ "ICPileupInfoProducer", "class_i_c_pileup_info_producer.html", "class_i_c_pileup_info_producer" ],
    [ "ICSecondaryVertexProducer", "class_i_c_secondary_vertex_producer.html", "class_i_c_secondary_vertex_producer" ],
    [ "ICSingleMetProducer", "class_i_c_single_met_producer.html", "class_i_c_single_met_producer" ],
    [ "ICSuperClusterProducer", "class_i_c_super_cluster_producer.html", "class_i_c_super_cluster_producer" ],
    [ "ICTauProducer< T >", "class_i_c_tau_producer.html", "class_i_c_tau_producer" ],
    [ "ICTrackProducer", "class_i_c_track_producer.html", "class_i_c_track_producer" ],
    [ "ICTriggerObjectProducer", "class_i_c_trigger_object_producer.html", "class_i_c_trigger_object_producer" ],
    [ "ICTriggerPathProducer", "class_i_c_trigger_path_producer.html", "class_i_c_trigger_path_producer" ],
    [ "ICVertexProducer", "class_i_c_vertex_producer.html", "class_i_c_vertex_producer" ],
    [ "ic::Jet", "classic_1_1_jet.html", "classic_1_1_jet" ],
    [ "JetDestHelper< U >", "struct_jet_dest_helper.html", "struct_jet_dest_helper" ],
    [ "JetDestHelper< ic::CaloJet >", "struct_jet_dest_helper_3_01ic_1_1_calo_jet_01_4.html", "struct_jet_dest_helper_3_01ic_1_1_calo_jet_01_4" ],
    [ "JetDestHelper< ic::JPTJet >", "struct_jet_dest_helper_3_01ic_1_1_j_p_t_jet_01_4.html", "struct_jet_dest_helper_3_01ic_1_1_j_p_t_jet_01_4" ],
    [ "JetDestHelper< ic::PFJet >", "struct_jet_dest_helper_3_01ic_1_1_p_f_jet_01_4.html", "struct_jet_dest_helper_3_01ic_1_1_p_f_jet_01_4" ],
    [ "JetSrcHelper< U >", "struct_jet_src_helper.html", "struct_jet_src_helper" ],
    [ "JetSrcHelper< pat::Jet >", "struct_jet_src_helper_3_01pat_1_1_jet_01_4.html", "struct_jet_src_helper_3_01pat_1_1_jet_01_4" ],
    [ "ic::JPTJet", "classic_1_1_j_p_t_jet.html", "classic_1_1_j_p_t_jet" ],
    [ "ic::LightTrack", "classic_1_1_light_track.html", "classic_1_1_light_track" ],
    [ "ch::syst::mass", "structch_1_1syst_1_1mass.html", "structch_1_1syst_1_1mass" ],
    [ "ic::Merge< T >", "classic_1_1_merge.html", "classic_1_1_merge" ],
    [ "ic::Met", "classic_1_1_met.html", "classic_1_1_met" ],
    [ "ic::Muon", "classic_1_1_muon.html", "classic_1_1_muon" ],
    [ "ch::Nuisance", "classch_1_1_nuisance.html", "classch_1_1_nuisance" ],
    [ "ch::Observation", "classch_1_1_observation.html", "classch_1_1_observation" ],
    [ "ch::Parameter", "classch_1_1_parameter.html", "classch_1_1_parameter" ],
    [ "ic::PFJet", "classic_1_1_p_f_jet.html", "classic_1_1_p_f_jet" ],
    [ "ic::Photon", "classic_1_1_photon.html", "classic_1_1_photon" ],
    [ "ic::PileupInfo", "classic_1_1_pileup_info.html", "classic_1_1_pileup_info" ],
    [ "ch::Process", "classch_1_1_process.html", "classch_1_1_process" ],
    [ "ch::syst::process", "structch_1_1syst_1_1process.html", "structch_1_1syst_1_1process" ],
    [ "ic::SecondaryVertex", "classic_1_1_secondary_vertex.html", "classic_1_1_secondary_vertex" ],
    [ "ch::SOverBInfo", "structch_1_1_s_over_b_info.html", "structch_1_1_s_over_b_info" ],
    [ "ic::StaticTree", "structic_1_1_static_tree.html", "structic_1_1_static_tree" ],
    [ "ic::SuperCluster", "classic_1_1_super_cluster.html", "classic_1_1_super_cluster" ],
    [ "ch::syst::SystMap< T >", "classch_1_1syst_1_1_syst_map.html", "classch_1_1syst_1_1_syst_map" ],
    [ "ch::syst::SystMapAsymm< T >", "classch_1_1syst_1_1_syst_map_asymm.html", "classch_1_1syst_1_1_syst_map_asymm" ],
    [ "ic::Tau", "classic_1_1_tau.html", "classic_1_1_tau" ],
    [ "ic::Track", "classic_1_1_track.html", "classic_1_1_track" ],
    [ "ic::TriggerObject", "classic_1_1_trigger_object.html", "classic_1_1_trigger_object" ],
    [ "ic::TriggerPath", "classic_1_1_trigger_path.html", "classic_1_1_trigger_path" ],
    [ "ic::Vertex", "classic_1_1_vertex.html", "classic_1_1_vertex" ]
];