var hierarchy =
[
    [ "ic::Met::BasicMet", "structic_1_1_met_1_1_basic_met.html", null ],
    [ "ic::Candidate", "classic_1_1_candidate.html", [
      [ "ic::CompositeCandidate", "classic_1_1_composite_candidate.html", null ],
      [ "ic::Electron", "classic_1_1_electron.html", null ],
      [ "ic::GenJet", "classic_1_1_gen_jet.html", null ],
      [ "ic::GenParticle", "classic_1_1_gen_particle.html", null ],
      [ "ic::Jet", "classic_1_1_jet.html", [
        [ "ic::CaloJet", "classic_1_1_calo_jet.html", [
          [ "ic::JPTJet", "classic_1_1_j_p_t_jet.html", null ]
        ] ],
        [ "ic::PFJet", "classic_1_1_p_f_jet.html", null ]
      ] ],
      [ "ic::L1TObject", "classic_1_1_l1_t_object.html", null ],
      [ "ic::Met", "classic_1_1_met.html", null ],
      [ "ic::Muon", "classic_1_1_muon.html", null ],
      [ "ic::PFCandidate", "classic_1_1_p_f_candidate.html", null ],
      [ "ic::Photon", "classic_1_1_photon.html", null ],
      [ "ic::Tau", "classic_1_1_tau.html", null ],
      [ "ic::TriggerObject", "classic_1_1_trigger_object.html", null ]
    ] ],
    [ "CollectionIDAndSize< T >", "struct_collection_i_d_and_size.html", null ],
    [ "CollectionSize< T >", "struct_collection_size.html", null ],
    [ "edm::ConsumesCollector", "structedm_1_1_consumes_collector.html", null ],
    [ "EDProducer", null, [
      [ "ic::Concatenate< T >", "classic_1_1_concatenate.html", null ],
      [ "ic::Merge< T >", "classic_1_1_merge.html", null ],
      [ "ICCandidateFromL1MuonProducer", "class_i_c_candidate_from_l1_muon_producer.html", null ],
      [ "ICCandidateProducer", "class_i_c_candidate_producer.html", null ],
      [ "ICConversionProducer", "class_i_c_conversion_producer.html", null ],
      [ "ICElectronConversionCalculator", "class_i_c_electron_conversion_calculator.html", null ],
      [ "ICElectronConversionFromPatCalculator", "class_i_c_electron_conversion_from_pat_calculator.html", null ],
      [ "ICElectronHcalDepthCalculator", "class_i_c_electron_hcal_depth_calculator.html", null ],
      [ "ICElectronIDMVAProducerMiniAOD", "class_i_c_electron_i_d_m_v_a_producer_mini_a_o_d.html", null ],
      [ "ICElectronProducer", "class_i_c_electron_producer.html", null ],
      [ "ICEventInfoProducer", "class_i_c_event_info_producer.html", null ],
      [ "ICEventProducer", "class_i_c_event_producer.html", null ],
      [ "ICGenJetProducer", "class_i_c_gen_jet_producer.html", null ],
      [ "ICGenParticleFromLHEParticlesProducer", "class_i_c_gen_particle_from_l_h_e_particles_producer.html", null ],
      [ "ICGenParticleProducer", "class_i_c_gen_particle_producer.html", null ],
      [ "ICGenTauProductProducer", "class_i_c_gen_tau_product_producer.html", null ],
      [ "ICGenVertexProducer", "class_i_c_gen_vertex_producer.html", null ],
      [ "ICHashTreeProducer", "class_i_c_hash_tree_producer.html", null ],
      [ "ICHttElecIsoCheck", "class_i_c_htt_elec_iso_check.html", null ],
      [ "ICHttMuonOverlapCheck", "class_i_c_htt_muon_overlap_check.html", null ],
      [ "ICJetFlavourCalculator", "class_i_c_jet_flavour_calculator.html", null ],
      [ "ICJetProducer< T, U >", "class_i_c_jet_producer.html", null ],
      [ "ICL1EtMissProducer", "class_i_c_l1_et_miss_producer.html", null ],
      [ "ICL1TObjectProducer< T >", "class_i_c_l1_t_object_producer.html", null ],
      [ "ICLeptonIsolation< T >", "class_i_c_lepton_isolation.html", null ],
      [ "ICLightTrackProducer", "class_i_c_light_track_producer.html", null ],
      [ "ICMetProducer< T >", "class_i_c_met_producer.html", null ],
      [ "ICMuonProducer", "class_i_c_muon_producer.html", null ],
      [ "ICPFCandidateProducer< T >", "class_i_c_p_f_candidate_producer.html", null ],
      [ "ICPhotonElectronConversionVetoFromPatCalculator", "class_i_c_photon_electron_conversion_veto_from_pat_calculator.html", null ],
      [ "ICPhotonElectronVetoCalculator", "class_i_c_photon_electron_veto_calculator.html", null ],
      [ "ICPhotonProducer", "class_i_c_photon_producer.html", null ],
      [ "ICPileupInfoProducer", "class_i_c_pileup_info_producer.html", null ],
      [ "ICSecondaryVertexProducer", "class_i_c_secondary_vertex_producer.html", null ],
      [ "ICSingleMetProducer", "class_i_c_single_met_producer.html", null ],
      [ "ICSuperClusterProducer", "class_i_c_super_cluster_producer.html", null ],
      [ "ICTauProducer< T >", "class_i_c_tau_producer.html", null ],
      [ "ICTrackProducer", "class_i_c_track_producer.html", null ],
      [ "ICTriggerObjectProducer", "class_i_c_trigger_object_producer.html", null ],
      [ "ICTriggerPathProducer", "class_i_c_trigger_path_producer.html", null ],
      [ "ICVertexProducer", "class_i_c_vertex_producer.html", null ],
      [ "RequestByDeltaR< T >", "class_request_by_delta_r.html", null ]
    ] ],
    [ "EGammaMvaEleEstimatorCSA14", "class_e_gamma_mva_ele_estimator_c_s_a14.html", null ],
    [ "ic::EventInfo", "classic_1_1_event_info.html", null ],
    [ "JetDestHelper< U >", "struct_jet_dest_helper.html", null ],
    [ "JetDestHelper< ic::CaloJet >", "struct_jet_dest_helper_3_01ic_1_1_calo_jet_01_4.html", null ],
    [ "JetDestHelper< ic::JPTJet >", "struct_jet_dest_helper_3_01ic_1_1_j_p_t_jet_01_4.html", null ],
    [ "JetDestHelper< ic::PFJet >", "struct_jet_dest_helper_3_01ic_1_1_p_f_jet_01_4.html", null ],
    [ "JetDestHelper< T >", "struct_jet_dest_helper.html", null ],
    [ "JetSrcHelper< U >", "struct_jet_src_helper.html", null ],
    [ "JetSrcHelper< pat::Jet >", "struct_jet_src_helper_3_01pat_1_1_jet_01_4.html", null ],
    [ "ic::LightTrack", "classic_1_1_light_track.html", null ],
    [ "ic::PileupInfo", "classic_1_1_pileup_info.html", null ],
    [ "ic::StaticTree", "structic_1_1_static_tree.html", null ],
    [ "ic::SuperCluster", "classic_1_1_super_cluster.html", null ],
    [ "ic::Track", "classic_1_1_track.html", null ],
    [ "ic::TriggerPath", "classic_1_1_trigger_path.html", null ],
    [ "ic::Unhash", "classic_1_1_unhash.html", null ],
    [ "ic::Vertex", "classic_1_1_vertex.html", [
      [ "ic::SecondaryVertex", "classic_1_1_secondary_vertex.html", null ]
    ] ]
];