var hierarchy =
[
    [ "ch::syst::analysis", "structch_1_1syst_1_1analysis.html", null ],
    [ "ch::syst::bin", "structch_1_1syst_1_1bin.html", null ],
    [ "ch::syst::bin_id", "classch_1_1syst_1_1bin__id.html", null ],
    [ "ic::Candidate", "classic_1_1_candidate.html", [
      [ "ic::CompositeCandidate", "classic_1_1_composite_candidate.html", null ],
      [ "ic::Electron", "classic_1_1_electron.html", null ],
      [ "ic::GenJet", "classic_1_1_gen_jet.html", null ],
      [ "ic::GenParticle", "classic_1_1_gen_particle.html", null ],
      [ "ic::Jet", "classic_1_1_jet.html", [
        [ "ic::CaloJet", "classic_1_1_calo_jet.html", [
          [ "ic::JPTJet", "classic_1_1_j_p_t_jet.html", null ]
        ] ],
        [ "ic::PFJet", "classic_1_1_p_f_jet.html", null ]
      ] ],
      [ "ic::Met", "classic_1_1_met.html", null ],
      [ "ic::Muon", "classic_1_1_muon.html", null ],
      [ "ic::Photon", "classic_1_1_photon.html", null ],
      [ "ic::Tau", "classic_1_1_tau.html", null ],
      [ "ic::TriggerObject", "classic_1_1_trigger_object.html", null ]
    ] ],
    [ "ch::syst::channel", "structch_1_1syst_1_1channel.html", null ],
    [ "ch::CombineHarvester", "classch_1_1_combine_harvester.html", null ],
    [ "EDProducer", null, [
      [ "ic::Concatenate< T >", "classic_1_1_concatenate.html", null ],
      [ "ic::Merge< T >", "classic_1_1_merge.html", null ],
      [ "ICCandidateProducer", "class_i_c_candidate_producer.html", null ],
      [ "ICElectronHcalDepthCalculator", "class_i_c_electron_hcal_depth_calculator.html", null ],
      [ "ICElectronProducer", "class_i_c_electron_producer.html", null ],
      [ "ICEventInfoProducer", "class_i_c_event_info_producer.html", null ],
      [ "ICEventProducer", "class_i_c_event_producer.html", null ],
      [ "ICGenJetProducer", "class_i_c_gen_jet_producer.html", null ],
      [ "ICGenParticleProducer", "class_i_c_gen_particle_producer.html", null ],
      [ "ICGenTauProductProducer", "class_i_c_gen_tau_product_producer.html", null ],
      [ "ICHttElecIsoCheck", "class_i_c_htt_elec_iso_check.html", null ],
      [ "ICHttMuonOverlapCheck", "class_i_c_htt_muon_overlap_check.html", null ],
      [ "ICJetFlavourCalculator", "class_i_c_jet_flavour_calculator.html", null ],
      [ "ICJetProducer< T, U >", "class_i_c_jet_producer.html", null ],
      [ "ICL1EtMissProducer", "class_i_c_l1_et_miss_producer.html", null ],
      [ "ICLightTrackProducer", "class_i_c_light_track_producer.html", null ],
      [ "ICMetProducer", "class_i_c_met_producer.html", null ],
      [ "ICMuonProducer", "class_i_c_muon_producer.html", null ],
      [ "ICPhotonElectronVetoCalculator", "class_i_c_photon_electron_veto_calculator.html", null ],
      [ "ICPhotonProducer", "class_i_c_photon_producer.html", null ],
      [ "ICPileupInfoProducer", "class_i_c_pileup_info_producer.html", null ],
      [ "ICSecondaryVertexProducer", "class_i_c_secondary_vertex_producer.html", null ],
      [ "ICSingleMetProducer", "class_i_c_single_met_producer.html", null ],
      [ "ICSuperClusterProducer", "class_i_c_super_cluster_producer.html", null ],
      [ "ICTauProducer< T >", "class_i_c_tau_producer.html", null ],
      [ "ICTrackProducer", "class_i_c_track_producer.html", null ],
      [ "ICTriggerObjectProducer", "class_i_c_trigger_object_producer.html", null ],
      [ "ICTriggerPathProducer", "class_i_c_trigger_path_producer.html", null ],
      [ "ICVertexProducer", "class_i_c_vertex_producer.html", null ]
    ] ],
    [ "ch::syst::era", "structch_1_1syst_1_1era.html", null ],
    [ "ic::EventInfo", "classic_1_1_event_info.html", null ],
    [ "ch::HistMapping", "structch_1_1_hist_mapping.html", null ],
    [ "JetDestHelper< U >", "struct_jet_dest_helper.html", null ],
    [ "JetDestHelper< ic::CaloJet >", "struct_jet_dest_helper_3_01ic_1_1_calo_jet_01_4.html", null ],
    [ "JetDestHelper< ic::JPTJet >", "struct_jet_dest_helper_3_01ic_1_1_j_p_t_jet_01_4.html", null ],
    [ "JetDestHelper< ic::PFJet >", "struct_jet_dest_helper_3_01ic_1_1_p_f_jet_01_4.html", null ],
    [ "JetDestHelper< T >", "struct_jet_dest_helper.html", null ],
    [ "JetSrcHelper< U >", "struct_jet_src_helper.html", null ],
    [ "JetSrcHelper< pat::Jet >", "struct_jet_src_helper_3_01pat_1_1_jet_01_4.html", null ],
    [ "ic::LightTrack", "classic_1_1_light_track.html", null ],
    [ "ch::syst::mass", "structch_1_1syst_1_1mass.html", null ],
    [ "ch::Nuisance", "classch_1_1_nuisance.html", null ],
    [ "ch::Observation", "classch_1_1_observation.html", null ],
    [ "ch::Parameter", "classch_1_1_parameter.html", null ],
    [ "ic::PileupInfo", "classic_1_1_pileup_info.html", null ],
    [ "ch::Process", "classch_1_1_process.html", null ],
    [ "ch::syst::process", "structch_1_1syst_1_1process.html", null ],
    [ "ch::SOverBInfo", "structch_1_1_s_over_b_info.html", null ],
    [ "ic::StaticTree", "structic_1_1_static_tree.html", null ],
    [ "ic::SuperCluster", "classic_1_1_super_cluster.html", null ],
    [ "ch::syst::SystMap< T >", "classch_1_1syst_1_1_syst_map.html", null ],
    [ "ch::syst::SystMapAsymm< T >", "classch_1_1syst_1_1_syst_map_asymm.html", null ],
    [ "ic::Track", "classic_1_1_track.html", null ],
    [ "ic::TriggerPath", "classic_1_1_trigger_path.html", null ],
    [ "ic::Vertex", "classic_1_1_vertex.html", [
      [ "ic::SecondaryVertex", "classic_1_1_secondary_vertex.html", null ]
    ] ]
];