#./bin/PlotCompare -p "Without-bias-weight:Without bias weight:./output/DY01_nobiasweight_et_0.root:ntuple:zptlhe:-1:2:4:20:0:200:wt_sign" -p "With-bias-weight:With bias weight:./output/DY01_biasweight_et_0.root:ntuple:zptlhe:-1:2:2:20:0:200:wt_sign" --norm_mode=3 --outname="zptlhe_noweights" --x_axis_title="LHE-level di-lepton p_{T} [GeV]" --big_label=" " --custom_y_axis_range=true --y_axis_min=0.0  --y_axis_title="a.u."
./bin/PlotCompare -p "Without-bias-weight:Without bias weight:./output/DY01_nobiasweight_100k_et_0.root:ntuple:zptlhe:-1:2:4:20:0:200:wt_sign" -p "With-bias-weight-1:With bias weight (1):./output/DY01_biasweight_100k_et_0.root:ntuple:zptlhe:-1:2:2:20:0:200:wt_sign" -p "With-bias-weight-2:With bias weight (2):./output/DY01_biasweight2_100k_et_0.root:ntuple:zptlhe:-1:2:1:20:0:200:wt_sign"  -p "With-bias-weight-3:With bias weight (3):./output/DY01_biasweight3_100k_et_0.root:ntuple:zptlhe:-1:2:12:20:0:200:wt_sign" --norm_mode=3 --outname="zptlhe_noweights" --x_axis_title="LHE-level di-lepton p_{T} [GeV]" --big_label=" " --y_axis_title="a.u." --custom_y_axis_range=true --y_axis_min=0.0  --y_axis_max=1


./bin/PlotCompare -p "Without-bias-weight:Without bias weight:./output/DY01_nobiasweight_100k_et_0.root:ntuple:zptlhe:-1:2:4:20:0:200:wt" -p "With-bias-weight-1:With bias weight (1):./output/DY01_biasweight_100k_et_0.root:ntuple:zptlhe:-1:2:2:20:0:200:wt" -p "With-bias-weight-2:With bias weight (2):./output/DY01_biasweight2_100k_et_0.root:ntuple:zptlhe:-1:2:1:20:0:200:wt"  -p "With-bias-weight-3:With bias weight (3):./output/DY01_biasweight3_100k_et_0.root:ntuple:zptlhe:-1:2:12:20:0:200:wt" --norm_mode=3 --outname="zptlhe_weights" --x_axis_title="LHE-level di-lepton p_{T} [GeV]" --big_label=" " --y_axis_title="a.u." --custom_y_axis_range=true --y_axis_min=0.0 --ratios "With-bias-weight-1/Without-bias-weight/2:With-bias-weight-2/Without-bias-weight/1:With-bias-weight-3/Without-bias-weight/12" --y_axis_max=1

./bin/PlotCompare -p "Without-bias-weight:Without bias weight:./output/DY01_nobiasweight_100k_et_0.root:ntuple:zptlhe:-1:2:4:20:0:200:wt" -p "With-bias-weight-1:With bias weight (1):./output/DY01_biasweight_100k_et_0.root:ntuple:zptlhe:-1:2:2:20:0:200:wt" -p "With-bias-weight-2:With bias weight (2):./output/DY01_biasweight2_100k_et_0.root:ntuple:zptlhe:-1:2:1:20:0:200:wt"  -p "With-bias-weight-3:With bias weight (3):./output/DY01_biasweight3_100k_et_0.root:ntuple:zptlhe:-1:2:12:20:0:200:wt" --norm_mode=3 --outname="zptlhe_weights_logy" --x_axis_title="LHE-level di-lepton p_{T} [GeV]" --big_label=" " --y_axis_title="a.u." --custom_y_axis_range=true --y_axis_min=0.0001 --ratios "With-bias-weight-1/Without-bias-weight/2:With-bias-weight-2/Without-bias-weight/1:With-bias-weight-3/Without-bias-weight/12" --y_axis_max=1 --log_y=true

./bin/PlotCompare -p "Without-bias-weight:Without bias weight:./output/DY01_nobiasweight_100k_et_0.root:ntuple:zptgen:-1:2:4:20:0:200:wt_sign" -p "With-bias-weight-1:With bias weight (1):./output/DY01_biasweight_100k_et_0.root:ntuple:zptgen:-1:2:2:20:0:200:wt_sign" -p "With-bias-weight-2:With bias weight (2):./output/DY01_biasweight2_100k_et_0.root:ntuple:zptgen:-1:2:1:20:0:200:wt_sign"  -p "With-bias-weight-3:With bias weight (3):./output/DY01_biasweight3_100k_et_0.root:ntuple:zptgen:-1:2:12:20:0:200:wt_sign" --norm_mode=3 --outname="zptgen_noweights" --x_axis_title="Gen-level di-lepton p_{T} [GeV]" --big_label=" " --y_axis_title="a.u." --custom_y_axis_range=true --y_axis_min=0.0  --y_axis_max=1


./bin/PlotCompare -p "Without-bias-weight:Without bias weight:./output/DY01_nobiasweight_100k_et_0.root:ntuple:zptgen:-1:2:4:20:0:200:wt" -p "With-bias-weight-1:With bias weight (1):./output/DY01_biasweight_100k_et_0.root:ntuple:zptgen:-1:2:2:20:0:200:wt" -p "With-bias-weight-2:With bias weight (2):./output/DY01_biasweight2_100k_et_0.root:ntuple:zptgen:-1:2:1:20:0:200:wt"  -p "With-bias-weight-3:With bias weight (3):./output/DY01_biasweight3_100k_et_0.root:ntuple:zptgen:-1:2:12:20:0:200:wt" --norm_mode=3 --outname="zptgen_weights" --x_axis_title="Gen-level di-lepton p_{T} [GeV]" --big_label=" " --y_axis_title="a.u." --custom_y_axis_range=true --y_axis_min=0.0 --ratios "With-bias-weight-1/Without-bias-weight/2:With-bias-weight-2/Without-bias-weight/1:With-bias-weight-3/Without-bias-weight/12" --y_axis_max=1

./bin/PlotCompare -p "Without-bias-weight:Without bias weight:./output/DY01_nobiasweight_100k_et_0.root:ntuple:zptgen:-1:2:4:20:0:200:wt" -p "With-bias-weight-1:With bias weight (1):./output/DY01_biasweight_100k_et_0.root:ntuple:zptgen:-1:2:2:20:0:200:wt" -p "With-bias-weight-2:With bias weight (2):./output/DY01_biasweight2_100k_et_0.root:ntuple:zptgen:-1:2:1:20:0:200:wt"  -p "With-bias-weight-3:With bias weight (3):./output/DY01_biasweight3_100k_et_0.root:ntuple:zptgen:-1:2:12:20:0:200:wt" --norm_mode=3 --outname="zptgen_weights_logy" --x_axis_title="Gen-level di-lepton p_{T} [GeV]" --big_label=" " --y_axis_title="a.u." --custom_y_axis_range=true --y_axis_min=0.0001 --ratios "With-bias-weight-1/Without-bias-weight/2:With-bias-weight-2/Without-bias-weight/1:With-bias-weight-3/Without-bias-weight/12" --y_axis_max=1 --log_y=true


#./bin/PlotCompare -p "Without-bias-weight:Without bias weight:./output/DY01_nobiasweight_et_0.root:ntuple:zmasslhe:-1:2:4:20:0:200:wt_sign" -p "With-bias-weight:With bias weight:./output/DY01_biasweight_et_0.root:ntuple:zmasslhe:-1:2:2:20:0:200:wt_sign" --norm_mode=3 --outname="zmasslhe_noweights" --x_axis_title="LHE-level di-lepton mass [GeV]" --big_label=" " --custom_y_axis_range=true --y_axis_min=0.0  --y_axis_title="a.u." --ratios "Without-bias-weight/With-bias-weight/2"

#./bin/PlotCompare -p "Without-bias-weight:Without bias weight:./output/DY01_nobiasweight_et_0.root:ntuple:zmasslhe:-1:2:4:20:0:200:wt" -p "With-bias-weight:With bias weight:./output/DY01_biasweight_et_0.root:ntuple:zmasslhe:-1:2:2:20:0:200:wt" --norm_mode=3 --outname="zmasslhe_weights" --x_axis_title="LHE-level di-lepton mass [GeV]" --big_label=" " --y_axis_title="a.u." --custom_y_axis_range=true --y_axis_min=0.0

