
ET_INC_SHIFT="  --draw_error_band=true --syst_tau_scale=CMS_scale_t_etau_8TeV --shift_tscale=0.32 --shift_backgrounds=ZTT:0.996753,QCD:1.018,W:0.962,ZL:0.911294,ZJ:0.959214,VV:0.967928,TT:0.88158 --auto_error_band=0.0404751"
MT_INC_SHIFT="  --draw_error_band=true --syst_tau_scale=CMS_scale_t_mutau_8TeV --shift_tscale=-0.13 --shift_backgrounds=ZTT:0.966278,QCD:1.0258,W:1.03862,ZL:1.15101,ZJ:1.19543,VV:0.97629,TT:1.07285 --auto_error_band=0.0398268"

./bin/HiggsHTohhPlot --cfg=scripts/new_plot_mssm_2012.cfg --channel=et --set_alias="sel:mt_1<30."   --method=8 --cat="inclusive" --var="n_prebjets_SF(5,-0.5,4.5)"  --x_axis_label="Number of b-tagged Jets"   --draw_ratio=true --log_y=true --extra_pad=500 --datacard="inclusive"   --background_scheme="et_default"  --custom_y_axis_min=true --y_axis_min=0.99 $ET_INC_SHIFT

./bin/HiggsHTohhPlot --cfg=scripts/new_plot_mssm_2012.cfg --channel=mt --set_alias="sel:mt_1<30."   --method=8 --cat="inclusive" --var="n_prebjets_SF(5,-0.5,4.5)"  --x_axis_label="Number of b-tagged Jets"   --draw_ratio=true --log_y=true --extra_pad=500 --datacard="inclusive"   --background_scheme="mt_with_zmm"  --custom_y_axis_min=true --y_axis_min=0.99 $MT_INC_SHIFT

./bin/HiggsHTohhPlot --cfg=scripts/new_plot_mssm_2012.cfg --channel=et --set_alias="sel:mt_1<30."   --method=8 --cat="inclusive" --var="n_prebjets(9,-0.5,8.5)"  --x_axis_label="Number of Jets"   --draw_ratio=true --log_y=true --extra_pad=500 --datacard="inclusive"   --background_scheme="et_default"  --custom_y_axis_min=true --y_axis_min=0.99 $ET_INC_SHIFT

./bin/HiggsHTohhPlot --cfg=scripts/new_plot_mssm_2012.cfg --channel=mt --set_alias="sel:mt_1<30."   --method=8 --cat="inclusive" --var="n_prebjets(9,-0.5,8.5)"  --x_axis_label="Number of Jets"   --draw_ratio=true --log_y=true --extra_pad=500 --datacard="inclusive"   --background_scheme="mt_with_zmm"  --custom_y_axis_min=true --y_axis_min=0.99 $MT_INC_SHIFT

./bin/HiggsHTohhPlot --cfg=scripts/new_plot_mssm_2012.cfg --channel=mt --set_alias="sel:mt_1<30."   --method=8 --cat="2jetinclusive" --var="prebjetbcsv_1(25,0,1)"   --x_axis_label="Leading selected jet CSV" --datacard="2jetinclusive"  --background_scheme="mt_with_zmm" --extra_pad=1.5 --draw_error_band=true --shift_backgrounds=ZTT:1.02294,QCD:1.07348,W:0.99610,ZL:1.00829,ZJ:1.00799,VV:1.01983,TT:1.01981 --auto_error_band=0.05172 --signal_scheme=" "

./bin/HiggsHTohhPlot --cfg=scripts/new_plot_mssm_2012.cfg --channel=mt --set_alias="sel:mt_1<30."   --method=8 --cat="2jetinclusive" --var="prebjetbcsv_2(25,0,1)"   --x_axis_label="Subleading selected jet CSV" --datacard="2jetinclusive"  --background_scheme="mt_with_zmm" --extra_pad=1.5 --draw_error_band=true --shift_backgrounds=ZTT:1.02294,QCD:1.07348,W:0.99610,ZL:1.00829,ZJ:1.00799,VV:1.01983,TT:1.01981 --auto_error_band=0.05172 --signal_scheme=" "

./bin/PlotCompare -p "M-ttbb:Without kinematic fit:datacard_mjj_tt_2jet2tagSFMassCuts_mt_2012.root:muTau_2jet2tagSFMassCuts:ggHTohhTo2Tau2B300:-1:2:2" -p "M-Hkinfit:With kinematic fit:datacard_m_H_hh_2jet2tagSFMassCuts_mt_2012.root:muTau_2jet2tagSFMassCuts:ggHTohhTo2Tau2B300:-1:2:4" --norm_mode=0 --big_label="#mu#tau_{h}" --outname="m_H_kinfit_vs_mttbb_2jet2tagSFMassCuts_mt_ggHTohh300" --x_axis_title="m_{H} [GeV]" --norm_bins=true  --custom_y_axis_min=true --y_axis_min=0.0 --custom_x_axis_range=true --x_axis_min=199.9  --x_axis_max=499.9

./bin/PlotCompare -p "M-H350:350GeV:datacard_m_H_hh_2jet2tagSFMassCuts_mt_2012.root:muTau_2jet2tagSFMassCuts:ggHTohhTo2Tau2B350:-1:2:604" -p "M-H300:300GeV:datacard_m_H_hh_2jet2tagSFMassCuts_mt_2012.root:muTau_2jet2tagSFMassCuts:ggHTohhTo2Tau2B300:-1:2:4" -p "M-H260:260GeV:datacard_m_H_hh_2jet2tagSFMassCuts_mt_2012.root:muTau_2jet2tagSFMassCuts:ggHTohhTo2Tau2B260:-1:2:868"  --norm_mode=0 --big_label="#mu#tau_{h}" --outname="m_H_kinfit_signalmasses_2jet2tagSFMassCuts_mt" --x_axis_title="m_{H}^{kinfit} [GeV]" --norm_bins=true  --custom_y_axis_min=true --y_axis_min=0.0 --custom_x_axis_range=true --x_axis_max=499.9


./bin/HiggsHTohhPlot --cfg=scripts/new_plot_mssm_2012.cfg --channel=mt   --method=15 --cat="2jet1tagSFMassCuts" --set_alias="sel:1" --var="mt_1(25,0,200)"   --x_axis_label="m_{T} [GeV]" --datacard="2jet1tagSFMassCuts" --extra_pad=1.5 --background_scheme="mt_with_zmm" --draw_error_band=true --auto_error_band=0.00001

./bin/HiggsHTohhPlot --cfg=scripts/new_plot_mssm_2012.cfg --channel=mt   --method=16 --cat="2jet2tagSFMassCuts" --set_alias="sel:1" --var="mt_1(25,0,200)"   --x_axis_label="m_{T} [GeV]" --datacard="2jet2tagSFMassCuts" --extra_pad=1.5 --background_scheme="mt_with_zmm" --draw_error_band=true --auto_error_band=0.00001



./bin/HiggsHTohhPlot --cfg=scripts/new_plot_mssm_2012.cfg --channel=mt --set_alias="sel:mt_1<30."   --method=8 --cat="2jet0tagMassCuts" --var="n_prebjets_SF(7,-0.5,6.5)"  --x_axis_label="Number of b-jets after b-tag SF"  --log_y=true --datacard="2jet0tagMassCuts"   --background_scheme="mt_with_zmm" --custom_y_axis_min=true --y_axis_min=0.0099 --extra_pad=100 --blind=true --x_blind_min=-0.5 --x_blind_max=5.5

./bin/HiggsHTohhPlot --cfg=scripts/new_plot_mssm_2012.cfg --channel=mt --set_alias="sel:mt_1<30."   --method=8 --cat="2jet1tagMassCuts" --var="n_prebjets_SF(7,-0.5,6.5)"  --x_axis_label="Number of b-jets after b-tag SF"  --log_y=true --datacard="2jet1tagMassCuts"   --background_scheme="mt_with_zmm" --custom_y_axis_min=true --y_axis_min=0.0099 --extra_pad=100 --blind=true --x_blind_min=-0.5 --x_blind_max=5.5

./bin/HiggsHTohhPlot --cfg=scripts/new_plot_mssm_2012.cfg --channel=mt --set_alias="sel:mt_1<30."   --method=8 --cat="2jet2tagMassCuts" --var="n_prebjets_SF(7,-0.5,6.5)"  --x_axis_label="Number of b-jets after b-tag SF"  --log_y=true --datacard="2jet2tagMassCuts"   --background_scheme="mt_with_zmm" --custom_y_axis_min=true --y_axis_min=0.0099 --extra_pad=100 --blind=true --x_blind_min=-0.5 --x_blind_max=5.5 --fix_negative_bins="QCD,W"

./bin/PlotCompare -p "ggHTohh300-central:H#rightarrowhh (m_{H}=300) JES Central:htt_mt.inputs-Hhh-8TeV-Preapproval.root:muTau_2jet2tag:ggHTohhTo2Tau2B300:-1:1:4" -p "ggHTohh300-JESup:H#rightarrowhh (m_{H}=300) JES Up:htt_mt.inputs-Hhh-8TeV-Preapproval.root:muTau_2jet2tag:ggHTohhTo2Tau2B300_CMS_scale_j_8TeVUp:-1:2:2" -p "ggHTohh300-JESdown:H#rightarrowhh (m_{H}=300) JES Down:htt_mt.inputs-Hhh-8TeV-Preapproval.root:muTau_2jet2tag:ggHTohhTo2Tau2B300_CMS_scale_j_8TeVDown:-1:2:4" --norm_mode=1 --big_label="#mu#tau_{h}"  --outname="ggHTohh300_jes_2jet2tag_mt" --x_axis_title="m_{H}^{kinfit}  [GeV]"  --norm_bins=true  --custom_y_axis_min=true --y_axis_min=0.0 --ratios="ggHTohh300-JESup/ggHTohh300-central/2:ggHTohh300-JESdown/ggHTohh300-central/4" --custom_x_axis_range=true --x_axis_min=200 --x_axis_max=599

./bin/PlotCompare -p "TT-central:t#bar{t} JES Central:htt_mt.inputs-Hhh-8TeV-Preapproval.root:muTau_2jet2tag:TT:-1:1:4" -p "TT-JESup:t#bar{t} JES Up:htt_mt.inputs-Hhh-8TeV-Preapproval.root:muTau_2jet2tag:TT_CMS_scale_j_8TeVUp:-1:2:2" -p "TT-JESdown:t#bar{t} JES Down:htt_mt.inputs-Hhh-8TeV-Preapproval.root:muTau_2jet2tag:TT_CMS_scale_j_8TeVDown:-1:2:4" --norm_mode=1 --big_label="#mu#tau_{h}"  --outname="TT_jes_2jet2tag_mt" --x_axis_title="m_{H}^{kinfit}  [GeV]"  --norm_bins=true  --custom_y_axis_min=true --y_axis_min=0.0 --ratios="TT-JESup/TT-central/2:TT-JESdown/TT-central/4"

./bin/PlotCompare -p "ggH125-central:H#rightarrow#tau#tau (m_{H}=125) Tau ES Central:htt_mt.inputs-sm-8TeV.root:muTau_1jet_high_lowhiggs:ggH_SM125:-1:1:4" -p "ggH125-TESup:H#rightarrow#tau#tau (m_{H}=125) Tau ES Up:htt_mt.inputs-sm-8TeV.root:muTau_1jet_high_lowhiggs:ggH_SM125_CMS_scale_t_mutau_8TeVUp:-1:2:2" -p "ggH125-TESdown:H#rightarrow#tau#tau (m_{H}=125) Tau ES Down:htt_mt.inputs-sm-8TeV.root:muTau_1jet_high_lowhiggs:ggH_SM125_CMS_scale_t_mutau_8TeVDown:-1:2:4" --norm_mode=1 --big_label="#mu#tau_{h}"  --outname="ggH125_taues_1jet_high_lowhiggs_mt" --x_axis_title="m_{#tau#tau}  [GeV]"  --norm_bins=true  --custom_y_axis_min=true --y_axis_min=0.0 --ratios="ggH125-TESup/ggH125-central/2:ggH125-TESdown/ggH125-central/4" --custom_x_axis_range=true --x_axis_min=50 --x_axis_max=220

./bin/PlotCompare -p "ZTT-central:Z#rightarrow#tau#tau Tau ES Central:htt_mt.inputs-sm-8TeV.root:muTau_1jet_high_lowhiggs:ZTT:-1:1:4" -p "ZTT-TESup:Z#rightarrow#tau#tau Tau ES Up:htt_mt.inputs-sm-8TeV.root:muTau_1jet_high_lowhiggs:ZTT_CMS_scale_t_mutau_8TeVUp:-1:2:2" -p "ZTT-TESdown:Z#rightarrow#tau#tau Tau ES Down:htt_mt.inputs-sm-8TeV.root:muTau_1jet_high_lowhiggs:ZTT_CMS_scale_t_mutau_8TeVDown:-1:2:4" --norm_mode=1 --big_label="#mu#tau_{h}"  --outname="ZTT_taues_1jet_high_lowhiggs_mt" --x_axis_title="m_{#tau#tau}  [GeV]"  --norm_bins=true  --custom_y_axis_min=true --y_axis_min=0.0 --ratios="ZTT-TESup/ZTT-central/2:ZTT-TESdown/ZTT-central/4" --custom_x_axis_range=true --x_axis_min=30 --x_axis_max=200
