#!/bin/sh

DO_MUONS=1
DO_ELECS=0

if [ ${DO_MUONS} -eq 1 ]; then

LABEL="ID_pt_eta_bins"; SMALL="eff.ID"; DIR="output/tag_and_probe_m_v3/${LABEL}"; TITLE="Medium HIP-safe ID"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py ZmmTP_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; python scripts/plotEffSlices.py ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.6,1.0 --ratio-to 1 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="IDTrk_pt_eta_bins"; SMALL="eff.IDTrk"; DIR="output/tag_and_probe_m_v3/${LABEL}"; TITLE="Medium HIP-safe ID"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py ZmmTP_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; python scripts/plotEffSlices.py ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.6,1.0 --ratio-to 1 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Iso_pt_eta_bins"; SMALL="eff.Iso"; DIR="output/tag_and_probe_m_v3/${LABEL}"; TITLE="Iso_{rel} < 0.15"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py ZmmTP_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; python scripts/plotEffSlices.py ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.6,1.0 --ratio-to 1 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="AIso1_pt_eta_bins"; SMALL="eff.AIso1"; DIR="output/tag_and_probe_m_v3/${LABEL}"; TITLE="Iso_{rel} #in [0.15,0.25]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py ZmmTP_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; python scripts/plotEffSlices.py ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.0,0.4 --ratio-y-range 0.02,1.98 --label-pos 2 --ratio-to 1 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="AIso2_pt_eta_bins"; SMALL="eff.AIso2"; DIR="output/tag_and_probe_m_v3/${LABEL}"; TITLE="Iso_{rel} #in [0.25,0.50]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py ZmmTP_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; python scripts/plotEffSlices.py ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.0,0.4 --ratio-y-range 0.02,1.98 --label-pos 2 --ratio-to 1 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Trg_Iso_pt_eta_bins"; SMALL="eff.Trg_Iso"; DIR="output/tag_and_probe_m_v3/${LABEL}"; TITLE="Trg IsoMu22"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py ZmmTP_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; python scripts/plotEffSlices.py ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 1 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="TrgOR_Iso_pt_eta_bins"; SMALL="eff.TrgOR_Iso"; DIR="output/tag_and_probe_m_v3/${LABEL}"; TITLE="IsoMu22 | IsoTkMu22"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py ZmmTP_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; python scripts/plotEffSlices.py ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 1 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="TrgOR3_Iso_pt_eta_bins"; SMALL="eff.TrgOR3_Iso"; DIR="output/tag_and_probe_m_v3/${LABEL}"; TITLE="IsoMu22 |IsoTkMu22 | Tau120"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py ZmmTP_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; python scripts/plotEffSlices.py ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 1 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="TrgMT_Iso_pt_eta_bins"; SMALL="eff.TrgMT_Iso"; DIR="output/tag_and_probe_m_v3/${LABEL}"; TITLE="IsoMu19PFTau20"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py ZmmTP_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; python scripts/plotEffSlices.py ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 1 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="TrgMTL1_Iso_pt_eta_bins"; SMALL="eff.TrgMTL1_Iso"; DIR="output/tag_and_probe_m_v3/${LABEL}"; TITLE="IsoMu19PFTau20SingleL1"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py ZmmTP_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; python scripts/plotEffSlices.py ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 1 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Trg_AIso1_pt_bins_inc_eta"; SMALL="eff.Trg_AIso1"; DIR="output/tag_and_probe_m_v3/${LABEL}"; TITLE="IsoMu22 | Iso_{rel} #in [0.15,0.25]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py ZmmTP_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; python scripts/plotEffSlices.py ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 1 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Trg_AIso2_pt_bins_inc_eta"; SMALL="eff.Trg_AIso2"; DIR="output/tag_and_probe_m_v3/${LABEL}"; TITLE="IsoMu22 | Iso_{rel} #in [0.25,0.50]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py ZmmTP_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; python scripts/plotEffSlices.py ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 1 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="TrgOR_AIso1_pt_bins_inc_eta"; SMALL="eff.TrgOR_AIso1"; DIR="output/tag_and_probe_m_v3/${LABEL}"; TITLE="Iso[Tk]Mu22 | Iso_{rel} #in [0.15,0.25]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py ZmmTP_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; python scripts/plotEffSlices.py ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 1 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="TrgOR_AIso2_pt_bins_inc_eta"; SMALL="eff.TrgOR_AIso2"; DIR="output/tag_and_probe_m_v3/${LABEL}"; TITLE="Iso[Tk]Mu22 | Iso_{rel} #in [0.25,0.50]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py ZmmTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py ZmmTP_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; python scripts/plotEffSlices.py ZmmTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' ZmmTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --ratio-to 1 --x-title "Muon p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

fi

if [ ${DO_ELECS} -eq 1 ]; then

LABEL="ID_pt_eta_bins"; SMALL="eff.ID"; DIR="output/tag_and_probe_e_v2/${LABEL}"; TITLE="Non-trig MVA ID"; BKG="CMSShape"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py ZeeTP_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; python scripts/plotEffSlices.py ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.6,1.0 --ratio-to 1 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Iso_pt_eta_bins"; SMALL="eff.Iso"; DIR="output/tag_and_probe_e_v2/${LABEL}"; TITLE="Iso_{rel} < 0.10"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py ZeeTP_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; python scripts/plotEffSlices.py ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.6,1.0 --ratio-to 1 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="AIso1_pt_eta_bins"; SMALL="eff.Iso"; DIR="output/tag_and_probe_e_v2/${LABEL}"; TITLE="Iso_{rel} #in [0.10,0.20]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py ZeeTP_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; python scripts/plotEffSlices.py ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.0,0.4 --ratio-y-range 0.02,1.98 --label-pos 2 --ratio-to 1 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="AIso2_pt_eta_bins"; SMALL="eff.Iso"; DIR="output/tag_and_probe_e_v2/${LABEL}"; TITLE="Iso_{rel} #in [0.20,0.50]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py ZeeTP_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; python scripts/plotEffSlices.py ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.0,0.4 --ratio-y-range 0.02,1.98 --label-pos 2 --ratio-to 1 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Trg_Iso_pt_eta_bins"; SMALL="eff.Trg_Iso"; DIR="output/tag_and_probe_e_v2/${LABEL}"; TITLE="Trg Ele25eta2p1WPTight"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py ZeeTP_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; python scripts/plotEffSlices.py ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.6,1.0 --ratio-to 1 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Trg_AIso1_pt_bins_inc_eta"; SMALL="eff.Trg_AIso1"; DIR="output/tag_and_probe_e_v2/${LABEL}"; TITLE="Trg Ele25eta2p1WPTight | Iso_{rel} #in [0.10,0.20]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py ZeeTP_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; python scripts/plotEffSlices.py ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 1 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}

LABEL="Trg_AIso2_pt_bins_inc_eta"; SMALL="eff.Trg_AIso2"; DIR="output/tag_and_probe_e_v2/${LABEL}"; TITLE="Trg Ele25eta2p1WPTight | Iso_{rel} #in [0.20,0.50]"; BKG="Exponential"; SIG="DoubleVCorr"; python scripts/fitTagAndProbe.py ZeeTP_Data.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/data; python scripts/fitTagAndProbe.py ZeeTP_DYJetsToLL.root:${LABEL} --bkg-model ${BKG} --sig-model ${SIG} --title "${TITLE}" -p ${DIR}/mc; python scripts/plotEffSlices.py ZeeTP_Data_Fits_${LABEL}.root:${LABEL}:'Title="Data"' ZeeTP_DYJetsToLL_Fits_${LABEL}.root:${LABEL}:'MarkerColor=2,LineColor=2,MarkerStyle=21,Title="MC"' --y-range 0.0,1.0 --label-pos 2 --ratio-to 1 --x-title "Electron p_{T} (GeV)" -o "${SMALL}" --title "${TITLE} Efficiency" --plot-dir ${DIR}
fi
