./bin/HiggsHTohhPlot --cfg=scripts/new_plot_mssm_2012.cfg --channel=em --set_alias="sel:met>80"   --method=8 --var="mt_1(40,0,240)" --cat="2jetGT1tagSF"   --x_axis_label="M_{T} [GeV]"  --norm_bins=false --datacard="2jetGT1tagSF"  --y_axis_label="Events"  --custom_y_axis_min=true --y_axis_min=0.0099   --blind=false --x_blind_min=200 --x_blind_max=400   --background_scheme="em_default" --verbosity=0 --signal_scheme=" " --draw_error_band=true --auto_error_band="0.00001" --draw_ratio=true

./bin/HiggsHTohhPlot --cfg=scripts/new_plot_mssm_2012.cfg --channel=em --set_alias="sel:met>80"   --method=8 --var="prebjetpt_1(40,0,200)" --cat="2jetGT1tagSF"   --x_axis_label="Lead b-jet p_{T} [GeV]"  --norm_bins=false --datacard="2jetGT1tagSF"  --y_axis_label="Events"  --custom_y_axis_min=true --y_axis_min=0.0099   --blind=false --x_blind_min=200 --x_blind_max=400   --background_scheme="em_default" --verbosity=0 --signal_scheme=" " --draw_error_band=true --auto_error_band="0.00001" --draw_ratio=true

./bin/HiggsHTohhPlot --cfg=scripts/new_plot_mssm_2012.cfg --channel=em --set_alias="sel:met>80"   --method=8 --var="prebjetpt_2(40,0,200)" --cat="2jetGT1tagSF"   --x_axis_label="Subleading b-jet p_{T} [GeV]"  --norm_bins=false --datacard="2jetGT1tagSF"  --y_axis_label="Events"  --custom_y_axis_min=true --y_axis_min=0.0099   --blind=false --x_blind_min=200 --x_blind_max=400   --background_scheme="em_default" --verbosity=0 --signal_scheme=" " --draw_error_band=true --auto_error_band="0.00001" --draw_ratio=true

./bin/HiggsHTohhPlot --cfg=scripts/new_plot_mssm_2012.cfg --channel=em --set_alias="sel:met>80"   --method=8 --var="prebjeteta_1(14,-2.8,2.8)" --cat="2jetGT1tagSF"   --x_axis_label="Lead b-jet #eta"  --norm_bins=false --datacard="2jetGT1tagSF"  --y_axis_label="Events"  --custom_y_axis_min=true --y_axis_min=0.0099   --blind=false --x_blind_min=200 --x_blind_max=400   --background_scheme="em_default" --verbosity=0 --signal_scheme=" " --draw_error_band=true --auto_error_band="0.00001" --extra_pad=1.5 --draw_ratio=true

./bin/HiggsHTohhPlot --cfg=scripts/new_plot_mssm_2012.cfg --channel=em --set_alias="sel:met>80"   --method=8 --var="prebjeteta_2(14,-2.8,2.8)" --cat="2jetGT1tagSF"   --x_axis_label="Subleading b-jet #eta"  --norm_bins=false --datacard="2jetGT1tagSF"  --y_axis_label="Events"  --custom_y_axis_min=true --y_axis_min=0.0099   --blind=false --x_blind_min=200 --x_blind_max=400   --background_scheme="em_default" --verbosity=0 --signal_scheme=" " --draw_error_band=true --auto_error_band="0.00001" --extra_pad=1.5 --draw_ratio=true

./bin/HiggsHTohhPlot --cfg=scripts/new_plot_mssm_2012.cfg --channel=em --set_alias="sel:met>80"   --method=8 --var="prebjet_deta(20,0,10)" --cat="2jetGT1tagSF"   --x_axis_label="#Delta#eta_{jj}"  --norm_bins=false --datacard="2jetGT1tagSF"  --y_axis_label="Events"  --custom_y_axis_min=true --y_axis_min=0.0099   --blind=false --x_blind_min=200 --x_blind_max=400   --background_scheme="em_default" --verbosity=0 --signal_scheme=" " --draw_error_band=true --auto_error_band="0.00001" --extra_pad=1.5 --draw_ratio=true

./bin/HiggsHTohhPlot --cfg=scripts/new_plot_mssm_2012.cfg --channel=em --set_alias="sel:met>80"   --method=8 --var="m_sv[0,10,20,30,40,50,60,70,80,90,100,110,120,130,140,150,160,170,180,190,200,225,250,275,300,325,350]" --cat="2jetGT1tagSF"   --x_axis_label="M_{#tau#tau} [GeV]"  --norm_bins=true --datacard="2jetGT1tagSF"  --y_axis_label="dN/dm_{#tau#tau} [1/GeV]"  --custom_y_axis_min=true --y_axis_min=0.0099  --draw_error_band=true --blind=false --x_blind_min=200 --x_blind_max=400   --background_scheme="em_default" --verbosity=0 --signal_scheme=" " --auto_error_band="0.00001" --extra_pad=1.2 --draw_ratio=true

./bin/HiggsHTohhPlot --cfg=scripts/new_plot_mssm_2012.cfg --channel=em --set_alias="sel:met>80"   --method=8 --var="prebjet_mjj(30,0,600)" --cat="2jetGT1tagSF"   --x_axis_label="M_{jj} [GeV]"  --norm_bins=true --datacard="2jetGT1tagSF"  --y_axis_label="dN/dm_{jj} [1/GeV]"  --custom_y_axis_min=true --y_axis_min=0.0099  --draw_error_band=true --blind=false --x_blind_min=200 --x_blind_max=400   --background_scheme="em_default" --verbosity=0 --signal_scheme=" " --auto_error_band="0.00001" --extra_pad=1.2 --draw_ratio=true

./bin/HiggsHTohhPlot --cfg=scripts/new_plot_mssm_2012.cfg --channel=em --set_alias="sel:met>80"   --method=8 --var="m_H_hh[200,250,270,290,310,330,350,370,390,410,430,450,500,550,600,650,700]" --cat="2jetGT1tagSF"   --x_axis_label="M_{H}^{kinfit} [GeV]"  --norm_bins=true --datacard="2jetGT1tagSF"  --y_axis_label="dN/dm_{H}^{kinfit} [1/GeV]"  --custom_y_axis_min=true --y_axis_min=0.0099  --draw_error_band=true --blind=false --x_blind_min=200 --x_blind_max=400   --background_scheme="em_default" --verbosity=0 --signal_scheme=" " --auto_error_band="0.00001" --fix_negative_bins="QCD" --extra_pad=1.2 --draw_ratio=true

#./bin/HiggsHTohhPlot --cfg=scripts/new_plot_mssm_2012.cfg --channel=mt --set_alias="sel:mt_1>100"   --method=8 --var="mt_1(40,0,240)" --cat="2jet2tagSF"   --x_axis_label="M_{T} [GeV]"  --norm_bins=false --datacard="2jet2tagSF"  --y_axis_label="Events"  --custom_y_axis_min=true --y_axis_min=0.0099   --blind=false --x_blind_min=200 --x_blind_max=400   --background_scheme="mt_with_zmm" --verbosity=0 --signal_scheme=" " --draw_error_band=true --auto_error_band="0.00001" --fix_negative_bins="QCD" --draw_ratio=true

#./bin/HiggsHTohhPlot --cfg=scripts/new_plot_mssm_2012.cfg --channel=mt --set_alias="sel:mt_1>100"   --method=8 --var="prebjetpt_1(20,0,200)" --cat="2jet2tagSF"   --x_axis_label="Lead b-jet p_{T} [GeV]"  --norm_bins=false --datacard="2jet2tagSF"  --y_axis_label="Events"  --custom_y_axis_min=true --y_axis_min=0.0099   --blind=false --x_blind_min=200 --x_blind_max=400   --background_scheme="mt_with_zmm" --verbosity=0 --signal_scheme=" " --draw_error_band=true --auto_error_band="0.00001" --fix_negative_bins="QCD" --draw_ratio=true

#./bin/HiggsHTohhPlot --cfg=scripts/new_plot_mssm_2012.cfg --channel=mt --set_alias="sel:mt_1>100"   --method=8 --var="prebjetpt_2(20,0,200)" --cat="2jet2tagSF"   --x_axis_label="Subleading b-jet p_{T} [GeV]"  --norm_bins=false --datacard="2jet2tagSF"  --y_axis_label="Events"  --custom_y_axis_min=true --y_axis_min=0.0099   --blind=false --x_blind_min=200 --x_blind_max=400   --background_scheme="mt_with_zmm" --verbosity=0 --signal_scheme=" " --draw_error_band=true --auto_error_band="0.00001" --fix_negative_bins="QCD" --draw_ratio=true

#./bin/HiggsHTohhPlot --cfg=scripts/new_plot_mssm_2012.cfg --channel=mt --set_alias="sel:mt_1>100"   --method=8 --var="prebjeteta_1(14,-2.8,2.8)" --cat="2jet2tagSF"   --x_axis_label="Lead b-jet #eta"  --norm_bins=false --datacard="2jet2tagSF"  --y_axis_label="Events"  --custom_y_axis_min=true --y_axis_min=0.0099   --blind=false --x_blind_min=200 --x_blind_max=400   --background_scheme="mt_with_zmm" --verbosity=0 --signal_scheme=" " --draw_error_band=true --auto_error_band="0.00001" --fix_negative_bins="QCD" --extra_pad=1.5 --draw_ratio=true

#./bin/HiggsHTohhPlot --cfg=scripts/new_plot_mssm_2012.cfg --channel=mt --set_alias="sel:mt_1>100"   --method=8 --var="prebjeteta_2(14,-2.8,2.8)" --cat="2jet2tagSF"   --x_axis_label="Subleading b-jet #eta"  --norm_bins=false --datacard="2jet2tagSF"  --y_axis_label="Events"  --custom_y_axis_min=true --y_axis_min=0.0099   --blind=false --x_blind_min=200 --x_blind_max=400   --background_scheme="mt_with_zmm" --verbosity=0 --signal_scheme=" " --draw_error_band=true --auto_error_band="0.00001" --fix_negative_bins="QCD" --extra_pad=1.5

#./bin/HiggsHTohhPlot --cfg=scripts/new_plot_mssm_2012.cfg --channel=mt --set_alias="sel:mt_1>100"   --method=8 --var="prebjet_deta(20,0,10)" --cat="2jet2tagSF"   --x_axis_label="#Delta#eta_{jj}"  --norm_bins=false --datacard="2jet2tagSF"  --y_axis_label="Events"  --custom_y_axis_min=true --y_axis_min=0.0099   --blind=false --x_blind_min=200 --x_blind_max=400   --background_scheme="mt_with_zmm" --verbosity=0 --signal_scheme=" " --draw_error_band=true --auto_error_band="0.00001" --fix_negative_bins="QCD" --extra_pad=1.5

#./bin/HiggsHTohhPlot --cfg=scripts/new_plot_mssm_2012.cfg --channel=mt --set_alias="sel:mt_1>100"   --method=8 --var="m_sv[0,20,40,60,80,100,120,140,160,180,200,250,300,350,400,450,500]" --cat="2jet2tagSF"   --x_axis_label="M_{#tau#tau} [GeV]"  --norm_bins=true --datacard="2jet2tagSF"  --y_axis_label="dN/dm_{#tau#tau} [1/GeV]"  --custom_y_axis_min=true --y_axis_min=0.0099  --draw_error_band=true --blind=false --x_blind_min=200 --x_blind_max=400   --background_scheme="mt_with_zmm" --verbosity=0 --signal_scheme=" " --auto_error_band="0.00001" --fix_negative_bins="QCD" --extra_pad=1.2

#./bin/HiggsHTohhPlot --cfg=scripts/new_plot_mssm_2012.cfg --channel=mt --set_alias="sel:mt_1>100"   --method=8 --var="prebjet_mjj(30,0,600)" --cat="2jet2tagSF"   --x_axis_label="M_{jj} [GeV]"  --norm_bins=true --datacard="2jet2tagSF"  --y_axis_label="dN/dm_{jj} [1/GeV]"  --custom_y_axis_min=true --y_axis_min=0.0099  --draw_error_band=true --blind=false --x_blind_min=200 --x_blind_max=400   --background_scheme="mt_with_zmm" --verbosity=0 --signal_scheme=" " --auto_error_band="0.00001" --fix_negative_bins="QCD" --extra_pad=1.2


#./bin/HiggsHTohhPlot --cfg=scripts/new_plot_mssm_2012.cfg --channel=mt --set_alias="sel:mt_1>100"   --method=8 --var="m_H_hh[200,250,270,290,310,330,350,370,390,410,430,450,500,550,600,650,700]" --cat="2jet2tagSF"   --x_axis_label="M_{H}^{kinfit} [GeV]"  --norm_bins=true --datacard="2jet2tagSF"  --y_axis_label="dN/dm_{H}^{kinfit} [1/GeV]"  --custom_y_axis_min=true --y_axis_min=0.0099  --draw_error_band=true --blind=false --x_blind_min=200 --x_blind_max=400   --background_scheme="mt_with_zmm" --verbosity=0 --signal_scheme=" " --auto_error_band="0.00001" --fix_negative_bins="QCD" --extra_pad=1.2
